package umasimulator.model.supportcard;

public enum Modifier {
    FRIENDSHIP_BONUS,
    SPEED_BONUS,
    POWER_BONUS,
    STAMINA_BONUS,
    GUTS_BONUS,
    WIT_BONUS,
    RACE_BONUS,
    FAN_BONUS,
    SKILL_POINT_BONUS,
    INITIAL_SPEED,
    INITIAL_POWER,
    INITIAL_STAMINA,
    INITIAL_GUTS,
    INITIAL_WIT,
    INITIAL_FRIENDSHIP,
    MOOD_EFFECT,
    TRAINING_EFFECT,
    EVENT_EFFECT,
    HINT_FREQUENCY,
    HINT_LEVELS,
    SPECIALTY_PRIORITY,
    FAILURE_PROTECTION,
    ENERGY_COST_REDUCTION,
    WIT_FRIENDSHIP_RECOVERY,
    EVENT_RECOVERY
}
